name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@master
      name: Checkout Code
     
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.0.0
      env:  
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      env:  
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
     
    - name: Restore NuGet Packages
      run: nuget restore WwiseTools.sln
 
    - name: Build and Publish
      run: msbuild WwiseTools.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
 
    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: published_webapp
        path: bin\Release\Publish
