name: Build 2019.2.4

on:
  push:
    branches: [ Wwise_2019.2.4 ]
  pull_request:
    branches: [ Wwise_2019.2.4 ]

jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@master
      name: Checkout Code
     
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.0.0
      env:  
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      env:  
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
     
    - name: Restore NuGet Packages
      run: nuget restore WwiseTools.sln
 
    - name: Build and Publish
      run: msbuild WwiseTools.sln
 
    - name: Upload Artifact
      uses: actions/upload-artifact@v2.3.0
      with:
        name: wwise_tools
        path: D:\a\WwiseTools\WwiseTools\WwiseTools\bin\Debug\*.dll
